// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CAI
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"cement")]
            public float Cement { get; set; }

            [ColumnName(@"slag")]
            public float Slag { get; set; }

            [ColumnName(@"flyash")]
            public float Flyash { get; set; }

            [ColumnName(@"water")]
            public float Water { get; set; }

            [ColumnName(@"superplasticizer")]
            public float Superplasticizer { get; set; }

            [ColumnName(@"coarseaggregate")]
            public float Coarseaggregate { get; set; }

            [ColumnName(@"fineaggregate")]
            public float Fineaggregate { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"csMPa")]
            public float CsMPa { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"cement")]
            public float Cement { get; set; }

            [ColumnName(@"slag")]
            public float Slag { get; set; }

            [ColumnName(@"flyash")]
            public float Flyash { get; set; }

            [ColumnName(@"water")]
            public float Water { get; set; }

            [ColumnName(@"superplasticizer")]
            public float Superplasticizer { get; set; }

            [ColumnName(@"coarseaggregate")]
            public float Coarseaggregate { get; set; }

            [ColumnName(@"fineaggregate")]
            public float Fineaggregate { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"csMPa")]
            public float CsMPa { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
