﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace CAI
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"cement", @"cement"),new InputOutputColumnPair(@"slag", @"slag"),new InputOutputColumnPair(@"flyash", @"flyash"),new InputOutputColumnPair(@"water", @"water"),new InputOutputColumnPair(@"superplasticizer", @"superplasticizer"),new InputOutputColumnPair(@"coarseaggregate", @"coarseaggregate"),new InputOutputColumnPair(@"fineaggregate", @"fineaggregate"),new InputOutputColumnPair(@"age", @"age")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"cement",@"slag",@"flyash",@"water",@"superplasticizer",@"coarseaggregate",@"fineaggregate",@"age"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.FastTreeTweedie(new FastTreeTweedieTrainer.Options(){NumberOfLeaves=79,MinimumExampleCountPerLeaf=20,NumberOfTrees=177,MaximumBinCountPerFeature=159,FeatureFraction=0.99999999,LearningRate=0.222523542881937,LabelColumnName=@"csMPa",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
